# Netlify Configuration for LogTrace

[build]
  # No build command needed - static site
  publish = "."

[[redirects]]
  # SPA-like routing - redirect all to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  # Cache static assets for 1 year
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/examples/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

